before_script:  
  - source /etc/profile

stages:  
  - build
  - test

run-build:  
  stage: build
  script:
    - apt-get install -y libncurses5-dev libglib2.0-dev libgeoip-dev libtokyocabinet-dev zlib1g-dev libncursesw5-dev libbz2-dev
    - autoreconf -fvi
    - cp COPYING debian/copyright
    - dpkg-buildpackage -us -uc
    - mkdir build
    - mv ../hello-urtk*.deb build/
test-build:  
  stage: test
  script:
    - dpkg -i build/hello-urtk*.deb

  only:
    - tags

  artifacts:
    paths:
      - build/*
